export const APP_CONSTANTS = {
  DEFAULT_AGE_LIMIT: 13,
  CAROUSEL_AUTO_SCROLL_INTERVAL: 3000,
  CAROUSEL_TRANSITION_DURATION: 500,
  MAX_TRENDING_ITEMS: 20,
  DEFAULT_ROWS_TO_SHOW: 2,
  ROWS_INCREMENT: 2,
} as const;

export const GAP_SIZES = {
  BASE: 12,
  MD: 16,
} as const;
